name: hyperlocal_emergency
description: Hyperlocal Emergency Skill Registry System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  # State management
  provider: ^6.1.1
  
  # HTTP client
  http: ^1.2.0
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Location & Geolocation
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.7.2
  
  # UI enhancements
  confetti: ^0.8.0

  
  # Font
  google_fonts: ^6.1.0
  
  # URL launcher for email
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - .env
  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

